version: 2

models:
  - name: dim_cars
    description: "Car dimension table with vehicle details"
    columns:
      - name: car_id
        description: "Surrogate key for car"
        tests:
          - unique
          - not_null
      - name: brand
        description: "Car brand/make"
      - name: model
        description: "Car model"
      - name: year
        description: "Manufacturing year"

  - name: fct_car_prices
    description: "Fact table for car pricing and metrics"
    columns:
      - name: car_id
        description: "Foreign key to dim_cars"
        tests:
          - not_null
      - name: price
        description: "Listed price"
        tests:
          - not_null
      - name: price_segment
        description: "Price category"
        tests:
          - accepted_values:
              values: ['budget', 'mid-range', 'premium', 'luxury']
